class Error(Exception):
    pass

class ConfError(Error):
    pass
